### ISSUE TITLE
画像の隙間をなくす。

### ISSUE THREAD

**Issue by aze-git** [aze-git/onlineskillup_step2#6]
方針１：画像表示箇所のサイズを固定サイズ化する。
方針２：画像を縦方向に詰めて表示させる。（レンガ状）

**Comment by aze-git** [comment]
Bootstrap4のcard-columnsで可能
https://getbootstrap.com/docs/4.0/components/card/#card-columns
https://unnikked.ga/masonry-like-grid-with-plain-bootstrap-85f8d023f743
https://codepen.io/jeserlin/pen/pmVZJj

**Comment by aze-git** [comment]
https://codepen.io/aze-git/pen/mYKPOw

**Comment by aze-git** [comment]
https://www.tipdip.jp/tips_posts/production/2268/
https://allabout.co.jp/gm/gc/402549/2/

**Comment by aze-git** [comment]
・https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.js のCDNをtemplateに加える。(jQueryより下の位置)
・home.jsを作成し、templateで読み込ませる。（masonryより下の位置）
・post.bladeに記載のJSをtemplateにうつす。（jQueryがかぶっているはずなので、削除する）
・CSS→JSの順で読み込ませるように、順番を見直す

**Comment by azepro1** [comment]
masonryだとうまくいかない（表示はうまくいくが、ランダム？にリンクやフォームボタンがクリックできなくなる）ので、Bootstrap4のcard-columnsで実装。
